;;; asdf-vm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from asdf-vm.el

(push (purecopy '(asdf-vm 0 1 0)) package--builtin-versions)


;;; Generated autoloads from asdf-vm-config.el

(register-definition-prefixes "asdf-vm-config" '("asdf-vm-"))


;;; Generated autoloads from asdf-vm-core.el

(register-definition-prefixes "asdf-vm-core" '("asdf-vm-"))


;;; Generated autoloads from asdf-vm-error.el

(register-definition-prefixes "asdf-vm-error" '("asdf-vm-"))


;;; Generated autoloads from asdf-vm-installer.el

(autoload 'asdf-vm-installer "asdf-vm-installer" "\
Install and activate VERSION of ASDF-VM.

When KEEP-DOWNLOADS is set, do not delete the downloaded source files,
this can be set interactively by setting a prefix value.

Sets `asdf-vm-process-executable' to the installed VERSION.

INTERACTIVE-CALL is an internal flag value and should not be used manually.

(fn VERSION &optional KEEP-DOWNLOADS INTERACTIVE-CALL)" t)
(register-definition-prefixes "asdf-vm-installer" '("asdf-vm-installer-"))


;;; Generated autoloads from asdf-vm-mode.el

(defvar asdf-vm-mode nil "\
Non-nil if Asdf-Vm mode is enabled.
See the `asdf-vm-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `asdf-vm-mode'.")
(custom-autoload 'asdf-vm-mode "asdf-vm-mode" nil)
(autoload 'asdf-vm-mode "asdf-vm-mode" "\
Minor mode for asdf-vm interaction.

\\{asdf-vm-mode-map}

This is a global minor mode.  If called interactively, toggle the
`Asdf-Vm mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='asdf-vm-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'asdf-vm-mode-enable "asdf-vm-mode" "\
Unconditionally enable `asdf-vm-mode'.")
(autoload 'asdf-vm-mode-disable "asdf-vm-mode" "\
Unconditionally disable `asdf-vm-mode'.")
(register-definition-prefixes "asdf-vm-mode" '("asdf-vm-"))


;;; Generated autoloads from asdf-vm-plugin.el

(register-definition-prefixes "asdf-vm-plugin" '("asdf-vm-plugin-"))


;;; Generated autoloads from asdf-vm-process.el

(autoload 'asdf-vm-call "asdf-vm-process" "\
Start or enqueue an ASDF-VM sub-process.

Returns the process or result of execution.

This is similar to `make-process' though the arguments carry special
meaning and defaults.

The keyword values for the PLIST are as follows:

:name NAME -- NAME is name for the process. When not provided a name
will be constructed from :name-prefix and :command.

:name-prefix NAME-PREFIX -- NAME-PREFIX is used in the construction of
NAME. It defaults to the `file-name-base' of :executable.

:executable EXECUTABLE -- EXECUTABLE is the path to the executable
program to be run in the sub-process. The values defaults to
`asdf-vm-process-executable'.

:executable-arguments EXECUTABLE-ARGUMENTS -- EXECUTABLE-ARGUMENTS is a
list of strings to be passed directly after :executable and before
:command in sub-process execution. This value defaults to
`asdf-vm-process-executable-arguments'.

:command COMMAND -- COMMAND a symbol or list of symbols representing the
sub-command of EXECUTABLE and is the first argument passed after
:executable-arguments.

:command-arguments COMMAND-ARGUMENTS -- COMMAND-ARGUMENTS is a list of
strings which is the argument values passed after :command during
sub-process execution.

:directory DIRECTORY -- DIRECTORY is the directory path in which the
sub-process is spawned. This value will default either to the parent of
the current buffer or, if there is not one, to `default-directory'.

:buffer-name BUFFER-NAME -- BUFFER-NAME is the name of the buffer which
hosts the spawned sub-process. This value defaults based on the kind of
execution occurring. For asynchronous called the value is
`asdf-vm-process-buffer-name' and for synchronous calls it is
`asdf-vm-process-output-buffer-name'.

:output OUTPUT -- OUTPUT is a boolean flag indicating that the
`asdf-vm-call' process should both block on execution and return the
string result from sub-process execution.

:blocking BLOCKING -- BLOCKING is a boolean flag indicate that the
`asdf-vm-call' should be made synchronously.

:success-codes SUCCESS-CODES -- SUCCESS-CODES is a list of integer
values between 1 and 255 which indicate sub-process execution success.
This list always has 0 pushed to the front.

When neither :blocking, nor :output is set to true, execution will be
enqueued for asynchronous execution. This execution starts immediately if
the queue is empty, otherwise it is kicked off immediately after the
completion of the previous asdf sub-process by `asdf-vm-process--sentinel'

(fn &rest PLIST)")
(register-definition-prefixes "asdf-vm-process" '("asdf-vm-"))


;;; Generated autoloads from asdf-vm-tool-versions.el

(register-definition-prefixes "asdf-vm-tool-versions" '("asdf-vm-tool-versions-"))


;;; Generated autoloads from asdf-vm-util.el

(register-definition-prefixes "asdf-vm-util" '("asdf-vm-"))

;;; End of scraped data

(provide 'asdf-vm-autoloads)

;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; asdf-vm-autoloads.el ends here
